// Simple bare-metal test for the AXI miner in Vitis (ARM PS running standalone).
// Assumes the AXI4-Lite slave is memory-mapped; update MINER_BASE as needed
// or rely on XPAR_AXI_MINER_0_S_AXI_BASEADDR generated by the BSP.
#include "xil_io.h"
#include "xil_printf.h"
#include "xparameters.h"

#ifndef MINER_BASE
#ifdef XPAR_AXI_MINER_0_S_AXI_BASEADDR
#define MINER_BASE XPAR_AXI_MINER_0_S_AXI_BASEADDR
#else
#define MINER_BASE 0x43C00000U
#endif
#endif

#define HDR_OFF    0x00  // 20 words (0x00..0x4C)
#define CTRL_OFF   0x50
#define STAT_OFF   0x54
#define TGT_OFF    0x58  // 8 words
#define HASH_OFF   0x78  // 8 words, read-only

static inline void miner_write(u32 off, u32 val) { Xil_Out32(MINER_BASE + off, val); }
static inline u32  miner_read(u32 off)           { return Xil_In32(MINER_BASE + off); }

int main(void) {
    xil_printf("AXI miner bare-metal smoke test\r\n");

    // Zero header (80 bytes -> 20 words)
    for (unsigned i = 0; i < 20; ++i) {
        miner_write(HDR_OFF + 4U * i, 0U);
    }
    // Loose target: all 0xFFFFFFFF so 'found' should assert.
    for (unsigned i = 0; i < 8; ++i) {
        miner_write(TGT_OFF + 4U * i, 0xFFFFFFFFU);
    }

    // Start bit
    miner_write(CTRL_OFF, 0x1);

    // Poll status: bit0=ready, bit1=busy, bit2=hash_valid, bit3=found
    u32 status;
    unsigned timeout = 1000000;
    do {
        status = miner_read(STAT_OFF);
    } while (((status & 0x4U) == 0U) && (--timeout));

    if (timeout == 0) {
        xil_printf("Timeout waiting for hash_valid\r\n");
        return -1;
    }

    // Read hash (big-endian words; word0 is MSW)
    u32 hash_words[8];
    for (unsigned i = 0; i < 8; ++i) {
        hash_words[i] = miner_read(HASH_OFF + 4U * i);
    }

    xil_printf("Hash: ");
    for (unsigned i = 0; i < 8; ++i) {
        xil_printf("%08lx", (unsigned long)hash_words[i]);
    }
    xil_printf("\r\n");

    xil_printf("found=%lu ready=%lu busy=%lu\r\n",
               (unsigned long)((status >> 3) & 1U),
               (unsigned long)(status & 1U),
               (unsigned long)((status >> 1) & 1U));

    // Expected hash for all-zero 80-byte header:
    // 4be7570e8f70eb093640c8468274ba759745a7aa2b7d25ab1e0421b259845014
    xil_printf("Expected: 4be7570e8f70eb093640c8468274ba759745a7aa2b7d25ab1e0421b259845014\r\n");
    return 0;
}
